name: '🐛 Community Problem'
labels: ['bug', 'community']
description: 'Something does not work as you expect in the community? Let us know!'

body:
  - type: textarea
    attributes:
      label: Issue
      description: Describe the issue, the actual and expected behaviors, and potential solutions here
    validations:
      required: true

  - type: textarea
    attributes:
      label: References
      description: Reference any relevant documentation, other materials or issues/pull requests that can be used for inspiration.
 
